GCLOUD_LOCATION: "us-central1"
GCLOUD_PROJECT_ID: "reflected-coder-475002-g1"
BACKEND_URL: "http://localhost:8081/chat"
STORAGE_BUCKET_NAME: "personal-expense-assistant-receipts-rushabh"
DB_COLLECTION_NAME: "personal-expense-assistant-receipts-rushabh"